"""Journal entry domain model.

A journal entry is a header (who, when, why) plus lines (which accounts,
how much). These classes do not depend on FastAPI or SQLAlchemy, so the
risk engine can be tested on its own.
"""

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from enum import StrEnum


class EntrySource(StrEnum):
    MANUAL = "MANUAL"  # keyed in by a person
    SYSTEM = "SYSTEM"  # generated by a subledger or batch job (AP, payroll, ...)
    RECURRING = "RECURRING"  # scheduled template, e.g. monthly rent accrual


@dataclass(frozen=True)
class JournalEntryLine:
    line_number: int
    account_number: str
    debit: Decimal
    credit: Decimal
    department: str | None = None
    vendor: str | None = None

    def __post_init__(self) -> None:
        for name in ("debit", "credit"):
            value = getattr(self, name)
            # Money must be Decimal: floats cannot represent most cents exactly.
            if not isinstance(value, Decimal):
                raise TypeError(f"{name} must be a Decimal, got {type(value).__name__}")
            if value < 0:
                raise ValueError(f"{name} cannot be negative: {value}")
        if self.debit and self.credit:
            raise ValueError("a line cannot have both a debit and a credit")
        if not self.debit and not self.credit:
            raise ValueError("a line must have either a debit or a credit")


@dataclass(frozen=True)
class JournalEntry:
    """A journal entry header and its lines.

    Creating an unbalanced entry is allowed on purpose: in client data an
    unbalanced entry is an audit finding to report, not a reason to crash.
    """

    entry_id: str
    posting_date: date  # GL date: the period the entry affects
    created_at: datetime  # when the entry was keyed into the system
    source: EntrySource
    description: str
    prepared_by: str
    approved_by: str | None
    currency: str
    lines: tuple[JournalEntryLine, ...]

    def __post_init__(self) -> None:
        # Store lines as a tuple so a frozen entry cannot be changed through its lines.
        object.__setattr__(self, "lines", tuple(self.lines))
        if not self.lines:
            raise ValueError(f"entry {self.entry_id} has no lines")
        line_numbers = [line.line_number for line in self.lines]
        if len(line_numbers) != len(set(line_numbers)):
            raise ValueError(f"entry {self.entry_id} has duplicate line numbers")

    @property
    def total_debit(self) -> Decimal:
        return sum((line.debit for line in self.lines), Decimal("0"))

    @property
    def total_credit(self) -> Decimal:
        return sum((line.credit for line in self.lines), Decimal("0"))

    @property
    def is_balanced(self) -> bool:
        return self.total_debit == self.total_credit

    @property
    def amount(self) -> Decimal:
        """Size of the entry used by amount-based rules: total debits."""
        return self.total_debit

    @property
    def account_numbers(self) -> frozenset[str]:
        return frozenset(line.account_number for line in self.lines)
